version: 2.1

workflows:
  workflow:
    jobs:
      - build-and-test:
          name: latest Node version
          run-lint: true
      - build-and-test:
          name: oldest supported Node version
          docker-image: circleci/node:6
          run-lint: false

jobs:
  build-and-test:
    parameters:
      run-lint:
        type: boolean
        default: false
      docker-image:
        type: string
        default: circleci/node:latest
    docker:
      - image: <<parameters.docker-image>>
      - image: redis
    steps:
      - checkout
      - run: echo "Node version:" `node --version`
      - run: npm install
      - run:
          command: npm test
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - run: npm run check-typescript
      - when:
          condition: <<parameters.run-lint>>
          steps:
            - run: npm run lint
      - run:
          name: dependency audit
          command: ./scripts/better-audit.sh
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
